[package]
name = "advent-of-rust"
version = "0.1.0"
authors = ["LOU Xun <aquarhead@ela.build>"]
edition = "2018"

[dependencies]
async-std = {version = "1.2", features = ["unstable"]}
futures = "0.3"
